#! /usr/bin/python
import sys
if (len(sys.argv) > 1):
    num=int(sys.argv[1])
else:
    num=int(raw_input("How many nodes are in your cluster? "))
print [str(((2**64 / num) * i) - 2**63) for i in range(num)]
